#' Continuous Fragility Index
#'
#' Implements the Continuous Fragility Index (CFI) of Caldwell, Youssefzadeh
#' and Limpisvasti (J Clin Epidemiol 2021;136:20-25) for two-arm trials with a
#' continuous outcome compared via Welch's t-test.
#'
#' The CFI is the minimum number of substitution iterations required to drive
#' a significant Welch t-test result to non-significance, where on each
#' iteration the data point in the higher-mean group that lies closest to but
#' still above that group's mean is moved into the lower-mean group.
#'
#' When raw data are unavailable, datasets matching the supplied summary
#' statistics are generated by rejection sampling and the procedure is
#' repeated `n_sim` times; the mean CFI across simulations is returned.
#'
#' @importFrom stats rnorm sd pt
#' @name continuous_fragility
NULL

#' Fast Welch's t-test p-value (two-sided)
#'
#' Equivalent to `stats::t.test(x, y)$p.value` with `var.equal = FALSE`,
#' but ~10x faster because it skips object construction and CI/estimate work.
#'
#' @noRd
fast_welch_p <- function(x, y) {
  nx <- length(x); ny <- length(y)
  if (nx < 2L || ny < 2L) return(NA_real_)
  mx <- sum(x) / nx; my <- sum(y) / ny
  vx <- sum((x - mx)^2) / (nx - 1L)
  vy <- sum((y - my)^2) / (ny - 1L)
  se2 <- vx / nx + vy / ny
  if (se2 <= 0) return(NA_real_)
  t  <- (mx - my) / sqrt(se2)
  df <- se2^2 / ((vx / nx)^2 / (nx - 1L) + (vy / ny)^2 / (ny - 1L))
  2 * stats::pt(-abs(t), df = df)
}

#' Core CFI iterative substitution algorithm on two numeric vectors
#'
#' @noRd
calc_cfi_from_vectors <- function(x, y, conf.level = 0.95, max_iter = NULL) {
  alpha <- 1 - conf.level
  p <- fast_welch_p(x, y)
  if (is.na(p) || p >= alpha) return(0L)

  if (is.null(max_iter)) max_iter <- length(x) + length(y)
  iter <- 0L

  repeat {
    if (mean(x) >= mean(y)) {
      high <- x; low <- y; from_x <- TRUE
    } else {
      high <- y; low <- x; from_x <- FALSE
    }
    m <- mean(high)
    above <- high[high > m]
    if (length(above) == 0L) break
    idx_in_above <- which.min(above - m)
    val <- above[idx_in_above]
    idx_in_high <- which(high == val)[1]

    high <- high[-idx_in_high]
    low  <- c(low, val)

    if (from_x) { x <- high; y <- low } else { y <- high; x <- low }

    iter <- iter + 1L
    p <- fast_welch_p(x, y)
    if (is.na(p) || p >= alpha) return(iter)
    if (iter >= max_iter) return(NA_integer_)
  }
  iter
}

#' Simulate a dataset matching target mean and SD via rejection sampling
#'
#' @noRd
simulate_arm <- function(n, target_mean, target_sd,
                         tol_mean = 0.01, tol_sd = 0.01,
                         max_tries = 1000L) {
  for (i in seq_len(max_tries)) {
    x <- stats::rnorm(n, mean = target_mean, sd = target_sd)
    if (abs(mean(x) - target_mean) <= tol_mean * max(1, abs(target_mean)) &&
        abs(stats::sd(x) - target_sd)  <= tol_sd  * max(1, abs(target_sd))) {
      return(x)
    }
  }
  # Fall back to a linearly-rescaled draw matching mean and SD exactly.
  x <- stats::rnorm(n, mean = 0, sd = 1)
  x <- (x - mean(x)) / stats::sd(x)
  x * target_sd + target_mean
}

#' Calculate Continuous Fragility Index from Summary Statistics (Helper)
#'
#' @noRd
calc_cfi_summary_single <- function(intervention_mean, control_mean,
                                    intervention_sd, control_sd,
                                    intervention_n, control_n,
                                    conf.level, n_sim, tol_mean, tol_sd) {
  if (any(is.na(c(intervention_mean, control_mean, intervention_sd,
                  control_sd, intervention_n, control_n)))) return(NA_real_)
  if (intervention_n < 2 || control_n < 2) return(NA_real_)

  intervention_n <- as.integer(intervention_n)
  control_n <- as.integer(control_n)
  vals <- integer(n_sim)
  for (i in seq_len(n_sim)) {
    x <- simulate_arm(intervention_n, intervention_mean, intervention_sd, tol_mean, tol_sd)
    y <- simulate_arm(control_n, control_mean, control_sd, tol_mean, tol_sd)
    vals[i] <- calc_cfi_from_vectors(x, y, conf.level = conf.level)
  }
  mean(vals)
}

#' Continuous Fragility Index from summary statistics
#'
#' Calculates the Continuous Fragility Index (Caldwell et al. 2021) from
#' two-arm summary statistics by simulating compatible datasets and applying
#' the iterative substitution algorithm.
#'
#' All arguments are vectorised, so this function can be called directly on
#' data frame columns inside `dplyr::mutate()` or `dplyr::case_when()` (as
#' well as on plain scalars), the same way [fragility_index_vec()] and
#' [reverse_fragility_index_vec()] are. Its argument structure mirrors
#' [fragility_index_vec()] (intervention/control pairs for each statistic),
#' just with mean/SD/n in place of event counts.
#'
#' @param intervention_mean,control_mean Mean outcome in the intervention and
#'   control groups.
#' @param intervention_sd,control_sd Standard deviation of the outcome in the
#'   intervention and control groups.
#' @param intervention_n,control_n Sample size of the intervention and
#'   control groups.
#' @param conf.level Confidence level for the Welch t-test (default `0.95`).
#' @param n_sim Number of simulated datasets to average over (default `5`,
#'   matching Caldwell et al.).
#' @param tol_mean,tol_sd Relative tolerances for rejection sampling.
#' @param seed Optional integer seed for reproducibility.
#'
#' @return A numeric vector (length matching the longest input) of mean CFI
#'   values across `n_sim` simulations. An element is `0` if the baseline
#'   Welch test is already non-significant and `NA_real_` if any of that
#'   element's inputs are missing.
#'
#' @references
#' Caldwell JE, Youssefzadeh K, Limpisvasti O. A method for calculating the
#' fragility index of continuous outcomes. *J Clin Epidemiol* 2021;136:20-25.
#'
#' @examples
#' continuous_fragility_index_summary(
#'   intervention_mean = 70, control_mean = 50,
#'   intervention_sd   = 10, control_sd   = 10,
#'   intervention_n    = 100, control_n   = 100,
#'   seed = 1
#' )
#' @export
continuous_fragility_index_summary <- function(intervention_mean, control_mean,
                                       intervention_sd, control_sd,
                                       intervention_n, control_n,
                                       conf.level = 0.95,
                                       n_sim = 5L,
                                       tol_mean = 0.01,
                                       tol_sd = 0.01,
                                       seed = NULL) {
  if (!is.null(seed)) set.seed(seed)

  args <- tibble::tibble(im = intervention_mean, cm = control_mean,
                         is_ = intervention_sd, cs = control_sd,
                         in_ = intervention_n, cn = control_n)

  purrr::pmap_dbl(args, function(im, cm, is_, cs, in_, cn) {
    calc_cfi_summary_single(im, cm, is_, cs, in_, cn,
                            conf.level = conf.level, n_sim = n_sim,
                            tol_mean = tol_mean, tol_sd = tol_sd)
  })
}

#' Continuous Fragility Index from raw outcome vectors
#'
#' Direct (non-simulated) CFI when raw per-patient outcomes are available.
#'
#' @param x,y Numeric vectors of outcome values for the intervention and
#'   control groups.
#' @param conf.level Confidence level for the Welch t-test (default `0.95`).
#'
#' @return A single integer: the number of substitution iterations required to
#'   lose significance, or `0` if the baseline test was non-significant.
#'
#' @examples
#' set.seed(1)
#' x <- rnorm(50, 70, 10)
#' y <- rnorm(50, 50, 10)
#' continuous_fragility_index_raw(x, y)
#' @export
continuous_fragility_index_raw <- function(x, y, conf.level = 0.95) {
  calc_cfi_from_vectors(as.numeric(x), as.numeric(y), conf.level = conf.level)
}

#' Vectorised Continuous Fragility Index
#'
#' [continuous_fragility_index_summary()] is itself vectorised, so this is
#' now a thin alias kept for backward compatibility.
#'
#' @param intervention_mean,control_mean,intervention_sd,control_sd,intervention_n,control_n
#'   Numeric vectors of summary statistics. See [continuous_fragility_index_summary()].
#' @param conf.level,n_sim,tol_mean,tol_sd See [continuous_fragility_index_summary()].
#'
#' @return A numeric vector of CFI values.
#' @export
continuous_fragility_index_vec <- function(intervention_mean, control_mean,
                                           intervention_sd, control_sd,
                                           intervention_n, control_n,
                                           conf.level = 0.95, n_sim = 5L,
                                           tol_mean = 0.01, tol_sd = 0.01) {
  continuous_fragility_index_summary(intervention_mean, control_mean,
                                     intervention_sd, control_sd,
                                     intervention_n, control_n,
                                     conf.level = conf.level, n_sim = n_sim,
                                     tol_mean = tol_mean, tol_sd = tol_sd)
}

#' Core reverse CFI algorithm on two numeric vectors
#'
#' Repeatedly draws one additional participant for each arm from the arm's
#' assumed normal distribution and counts how many pairs must be added before
#' the Welch t-test reaches significance.
#'
#' @noRd
calc_rcfi_from_vectors <- function(x, y, mean_x, sd_x, mean_y, sd_y,
                                   conf.level = 0.95, max_iter = 10000L) {
  alpha <- 1 - conf.level
  p <- fast_welch_p(x, y)
  if (!is.na(p) && p < alpha) return(0L)

  for (iter in seq_len(max_iter)) {
    x <- c(x, stats::rnorm(1, mean_x, sd_x))
    y <- c(y, stats::rnorm(1, mean_y, sd_y))
    p <- fast_welch_p(x, y)
    if (!is.na(p) && p < alpha) return(iter)
  }
  NA_integer_
}

#' Calculate Reverse Continuous Fragility Index from Summary Statistics (Helper)
#'
#' @noRd
calc_rcfi_summary_single <- function(intervention_mean, control_mean,
                                     intervention_sd, control_sd,
                                     intervention_n, control_n,
                                     conf.level, n_sim, tol_mean, tol_sd,
                                     max_iter) {
  if (any(is.na(c(intervention_mean, control_mean, intervention_sd,
                  control_sd, intervention_n, control_n)))) return(NA_real_)
  if (intervention_n < 2 || control_n < 2) return(NA_real_)

  intervention_n <- as.integer(intervention_n)
  control_n <- as.integer(control_n)
  vals <- numeric(n_sim)
  for (i in seq_len(n_sim)) {
    x <- simulate_arm(intervention_n, intervention_mean, intervention_sd, tol_mean, tol_sd)
    y <- simulate_arm(control_n, control_mean, control_sd, tol_mean, tol_sd)
    vals[i] <- calc_rcfi_from_vectors(x, y, intervention_mean, intervention_sd,
                                      control_mean, control_sd,
                                      conf.level = conf.level,
                                      max_iter = max_iter)
  }
  mean(vals)
}

#' Reverse Continuous Fragility Index
#'
#' Estimates how many additional participants per arm would have been required
#' to render a non-significant Welch t-test significant, given two-arm summary
#' statistics. This is a continuous-outcome analogue of the reverse fragility
#' index for dichotomous outcomes: a measure of how far a non-significant
#' trial was from significance, expressed in participants per arm.
#'
#' If the original test is already significant the function returns `0`.
#' Otherwise additional participants are sampled from each arm's assumed
#' normal distribution (parameterised by the supplied mean and SD) and added
#' one per arm per iteration until significance is reached. The procedure is
#' repeated `n_sim` times and the mean is returned.
#'
#' All arguments are vectorised, so this function can be called directly on
#' data frame columns inside `dplyr::mutate()` or `dplyr::case_when()` (as
#' well as on plain scalars), the same way [fragility_index_vec()] and
#' [reverse_fragility_index_vec()] are. Its argument structure mirrors
#' [reverse_fragility_index_vec()] (intervention/control pairs for each
#' statistic), just with mean/SD/n in place of event counts.
#'
#' @param intervention_mean,control_mean Mean outcome in the intervention and
#'   control groups.
#' @param intervention_sd,control_sd Standard deviation of the outcome in the
#'   intervention and control groups.
#' @param intervention_n,control_n Sample size of the intervention and
#'   control groups.
#' @param conf.level Confidence level for the Welch t-test (default `0.95`).
#' @param n_sim Number of simulated datasets to average over (default `5`).
#' @param tol_mean,tol_sd Relative tolerances for rejection sampling.
#' @param max_iter Maximum additional participants per arm before giving up
#'   and returning `NA_real_` (default `10000`).
#' @param seed Optional integer seed for reproducibility.
#'
#' @return A numeric vector (length matching the longest input) of mean
#'   additional participants per arm required to reach significance across
#'   `n_sim` simulations. An element is `0` if that element's original test
#'   was already significant.
#'
#' @examples
#' reverse_continuous_fragility_index_summary(
#'   intervention_mean = 55, control_mean = 50,
#'   intervention_sd   = 10, control_sd   = 10,
#'   intervention_n    = 30, control_n    = 30,
#'   seed = 1
#' )
#' @export
reverse_continuous_fragility_index_summary <- function(intervention_mean, control_mean,
                                               intervention_sd, control_sd,
                                               intervention_n, control_n,
                                               conf.level = 0.95,
                                               n_sim = 5L,
                                               tol_mean = 0.01,
                                               tol_sd = 0.01,
                                               max_iter = 10000L,
                                               seed = NULL) {
  if (!is.null(seed)) set.seed(seed)

  args <- tibble::tibble(im = intervention_mean, cm = control_mean,
                         is_ = intervention_sd, cs = control_sd,
                         in_ = intervention_n, cn = control_n)

  purrr::pmap_dbl(args, function(im, cm, is_, cs, in_, cn) {
    calc_rcfi_summary_single(im, cm, is_, cs, in_, cn,
                             conf.level = conf.level, n_sim = n_sim,
                             tol_mean = tol_mean, tol_sd = tol_sd,
                             max_iter = max_iter)
  })
}

#' Vectorised Reverse Continuous Fragility Index
#'
#' [reverse_continuous_fragility_index_summary()] is itself vectorised, so
#' this is now a thin alias kept for backward compatibility.
#'
#' @param intervention_mean,control_mean,intervention_sd,control_sd,intervention_n,control_n
#'   Numeric vectors of summary statistics. See
#'   [reverse_continuous_fragility_index_summary()].
#' @param conf.level,n_sim,tol_mean,tol_sd,max_iter See
#'   [reverse_continuous_fragility_index_summary()].
#'
#' @return A numeric vector of reverse CFI values.
#' @export
reverse_continuous_fragility_index_vec <- function(intervention_mean, control_mean,
                                                   intervention_sd, control_sd,
                                                   intervention_n, control_n,
                                                   conf.level = 0.95,
                                                   n_sim = 5L,
                                                   tol_mean = 0.01,
                                                   tol_sd = 0.01,
                                                   max_iter = 10000L) {
  reverse_continuous_fragility_index_summary(intervention_mean, control_mean,
                                             intervention_sd, control_sd,
                                             intervention_n, control_n,
                                             conf.level = conf.level,
                                             n_sim = n_sim,
                                             tol_mean = tol_mean,
                                             tol_sd = tol_sd,
                                             max_iter = max_iter)
}

#' Reverse Continuous Fragility Index for a Data Frame
#'
#' Adds a reverse Continuous Fragility Index column to a data frame of trial
#' summary statistics.
#'
#' @param data A data frame or tibble.
#' @param intervention_mean,control_mean Unquoted column names for the
#'   intervention and control group means.
#' @param intervention_sd,control_sd Unquoted column names for the
#'   intervention and control group standard deviations.
#' @param intervention_n,control_n Unquoted column names for the
#'   intervention and control group sample sizes.
#' @param conf.level,n_sim,tol_mean,tol_sd,max_iter See
#'   [reverse_continuous_fragility_index_summary()].
#' @param col_name Output column name (default
#'   `"reverse_continuous_fragility_index"`).
#'
#' @return The input data frame with an additional reverse CFI column.
#' @export
reverse_continuous_fragility_index <- function(data,
                                                    intervention_mean, control_mean,
                                                    intervention_sd, control_sd,
                                                    intervention_n, control_n,
                                                    conf.level = 0.95,
                                                    n_sim = 5L,
                                                    tol_mean = 0.01,
                                                    tol_sd = 0.01,
                                                    max_iter = 10000L,
                                                    col_name = "reverse_continuous_fragility_index") {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  col_name_sym <- rlang::sym(col_name)
  data %>%
    dplyr::mutate(
      !!col_name_sym := reverse_continuous_fragility_index_vec(
        {{ intervention_mean }}, {{ control_mean }},
        {{ intervention_sd }}, {{ control_sd }},
        {{ intervention_n }}, {{ control_n }},
        conf.level = conf.level, n_sim = n_sim,
        tol_mean = tol_mean, tol_sd = tol_sd,
        max_iter = max_iter
      )
    )
}

#' Continuous Fragility Index for a Data Frame
#'
#' Adds a Continuous Fragility Index column to a data frame of trial summary
#' statistics. Supports tidy evaluation.
#'
#' @param data A data frame or tibble.
#' @param intervention_mean,control_mean Unquoted column names for the
#'   intervention and control group means.
#' @param intervention_sd,control_sd Unquoted column names for the
#'   intervention and control group standard deviations.
#' @param intervention_n,control_n Unquoted column names for the
#'   intervention and control group sample sizes.
#' @param conf.level,n_sim,tol_mean,tol_sd See
#'   [continuous_fragility_index_summary()].
#' @param col_name Name of the output column (default
#'   `"continuous_fragility_index"`).
#'
#' @return The input data frame with an additional CFI column.
#' @export
continuous_fragility_index <- function(data,
                                            intervention_mean, control_mean,
                                            intervention_sd, control_sd,
                                            intervention_n, control_n,
                                            conf.level = 0.95,
                                            n_sim = 5L,
                                            tol_mean = 0.01,
                                            tol_sd = 0.01,
                                            col_name = "continuous_fragility_index") {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  col_name_sym <- rlang::sym(col_name)
  data %>%
    dplyr::mutate(
      !!col_name_sym := continuous_fragility_index_vec(
        {{ intervention_mean }}, {{ control_mean }},
        {{ intervention_sd }}, {{ control_sd }},
        {{ intervention_n }}, {{ control_n }},
        conf.level = conf.level, n_sim = n_sim,
        tol_mean = tol_mean, tol_sd = tol_sd
      )
    )
}
