#' Continuous Fragility Index
#'
#' Implements the Continuous Fragility Index (CFI) of Caldwell, Youssefzadeh
#' and Limpisvasti (J Clin Epidemiol 2021;136:20-25) for two-arm trials with a
#' continuous outcome compared via Welch's t-test.
#'
#' The CFI is the minimum number of substitution iterations required to drive
#' a significant Welch t-test result to non-significance, where on each
#' iteration the data point in the higher-mean group that lies closest to but
#' still above that group's mean is moved into the lower-mean group.
#'
#' When raw data are unavailable, datasets matching the supplied summary
#' statistics are generated by rejection sampling and the procedure is
#' repeated `n_sim` times; the mean CFI across simulations is returned.
#'
#' @importFrom stats rnorm sd pt
#' @name continuous_fragility
NULL

#' Fast Welch's t-test p-value (two-sided)
#'
#' Equivalent to `stats::t.test(x, y)$p.value` with `var.equal = FALSE`,
#' but ~10x faster because it skips object construction and CI/estimate work.
#'
#' @noRd
fast_welch_p <- function(x, y) {
  nx <- length(x); ny <- length(y)
  if (nx < 2L || ny < 2L) return(NA_real_)
  mx <- sum(x) / nx; my <- sum(y) / ny
  vx <- sum((x - mx)^2) / (nx - 1L)
  vy <- sum((y - my)^2) / (ny - 1L)
  se2 <- vx / nx + vy / ny
  if (se2 <= 0) return(NA_real_)
  t  <- (mx - my) / sqrt(se2)
  df <- se2^2 / ((vx / nx)^2 / (nx - 1L) + (vy / ny)^2 / (ny - 1L))
  2 * stats::pt(-abs(t), df = df)
}

#' Core CFI iterative substitution algorithm on two numeric vectors
#'
#' @noRd
calc_cfi_from_vectors <- function(x, y, conf.level = 0.95, max_iter = NULL) {
  alpha <- 1 - conf.level
  p <- fast_welch_p(x, y)
  if (is.na(p) || p >= alpha) return(0L)

  if (is.null(max_iter)) max_iter <- length(x) + length(y)
  iter <- 0L

  repeat {
    if (mean(x) >= mean(y)) {
      high <- x; low <- y; from_x <- TRUE
    } else {
      high <- y; low <- x; from_x <- FALSE
    }
    m <- mean(high)
    above <- high[high > m]
    if (length(above) == 0L) break
    idx_in_above <- which.min(above - m)
    val <- above[idx_in_above]
    idx_in_high <- which(high == val)[1]

    high <- high[-idx_in_high]
    low  <- c(low, val)

    if (from_x) { x <- high; y <- low } else { y <- high; x <- low }

    iter <- iter + 1L
    p <- fast_welch_p(x, y)
    if (is.na(p) || p >= alpha) return(iter)
    if (iter >= max_iter) return(NA_integer_)
  }
  iter
}

#' Simulate a dataset matching target mean and SD via rejection sampling
#'
#' @noRd
simulate_arm <- function(n, target_mean, target_sd,
                         tol_mean = 0.01, tol_sd = 0.01,
                         max_tries = 1000L) {
  for (i in seq_len(max_tries)) {
    x <- stats::rnorm(n, mean = target_mean, sd = target_sd)
    if (abs(mean(x) - target_mean) <= tol_mean * max(1, abs(target_mean)) &&
        abs(stats::sd(x) - target_sd)  <= tol_sd  * max(1, abs(target_sd))) {
      return(x)
    }
  }
  # Fall back to a linearly-rescaled draw matching mean and SD exactly.
  x <- stats::rnorm(n, mean = 0, sd = 1)
  x <- (x - mean(x)) / stats::sd(x)
  x * target_sd + target_mean
}

#' Continuous Fragility Index from summary statistics
#'
#' Calculates the Continuous Fragility Index (Caldwell et al. 2021) from
#' two-arm summary statistics by simulating compatible datasets and applying
#' the iterative substitution algorithm.
#'
#' @param mean1,sd1,n1 Mean, standard deviation, and sample size of arm 1.
#' @param mean2,sd2,n2 Mean, standard deviation, and sample size of arm 2.
#' @param conf.level Confidence level for the Welch t-test (default `0.95`).
#' @param n_sim Number of simulated datasets to average over (default `5`,
#'   matching Caldwell et al.).
#' @param tol_mean,tol_sd Relative tolerances for rejection sampling.
#' @param seed Optional integer seed for reproducibility.
#'
#' @return A single numeric value: the mean CFI across `n_sim` simulations.
#'   Returns `0` if the baseline Welch test is already non-significant and
#'   `NA_real_` if any input is missing.
#'
#' @references
#' Caldwell JE, Youssefzadeh K, Limpisvasti O. A method for calculating the
#' fragility index of continuous outcomes. *J Clin Epidemiol* 2021;136:20-25.
#'
#' @examples
#' continuous_fragility_index(
#'   mean1 = 70, sd1 = 10, n1 = 100,
#'   mean2 = 50, sd2 = 10, n2 = 100,
#'   seed  = 1
#' )
#' @export
continuous_fragility_index <- function(mean1, sd1, n1,
                                       mean2, sd2, n2,
                                       conf.level = 0.95,
                                       n_sim = 5L,
                                       tol_mean = 0.01,
                                       tol_sd = 0.01,
                                       seed = NULL) {
  if (any(is.na(c(mean1, sd1, n1, mean2, sd2, n2)))) return(NA_real_)
  if (n1 < 2 || n2 < 2) return(NA_real_)
  if (!is.null(seed)) set.seed(seed)

  n1 <- as.integer(n1); n2 <- as.integer(n2)
  vals <- integer(n_sim)
  for (i in seq_len(n_sim)) {
    x <- simulate_arm(n1, mean1, sd1, tol_mean, tol_sd)
    y <- simulate_arm(n2, mean2, sd2, tol_mean, tol_sd)
    vals[i] <- calc_cfi_from_vectors(x, y, conf.level = conf.level)
  }
  mean(vals)
}

#' Continuous Fragility Index from raw outcome vectors
#'
#' Direct (non-simulated) CFI when raw per-patient outcomes are available.
#'
#' @param x,y Numeric vectors of outcome values for arms 1 and 2.
#' @param conf.level Confidence level for the Welch t-test (default `0.95`).
#'
#' @return A single integer: the number of substitution iterations required to
#'   lose significance, or `0` if the baseline test was non-significant.
#'
#' @examples
#' set.seed(1)
#' x <- rnorm(50, 70, 10)
#' y <- rnorm(50, 50, 10)
#' continuous_fragility_index_raw(x, y)
#' @export
continuous_fragility_index_raw <- function(x, y, conf.level = 0.95) {
  calc_cfi_from_vectors(as.numeric(x), as.numeric(y), conf.level = conf.level)
}

#' Vectorised Continuous Fragility Index
#'
#' Vectorised wrapper around [continuous_fragility_index()] for use inside
#' `dplyr::mutate()`.
#'
#' @param mean1,sd1,n1,mean2,sd2,n2 Numeric vectors of summary statistics.
#' @param conf.level,n_sim,tol_mean,tol_sd See [continuous_fragility_index()].
#'
#' @return A numeric vector of CFI values.
#' @export
continuous_fragility_index_vec <- function(mean1, sd1, n1, mean2, sd2, n2,
                                           conf.level = 0.95, n_sim = 5L,
                                           tol_mean = 0.01, tol_sd = 0.01) {
  args <- tibble::tibble(m1 = mean1, s1 = sd1, k1 = n1,
                         m2 = mean2, s2 = sd2, k2 = n2)
  purrr::pmap_dbl(args, function(m1, s1, k1, m2, s2, k2) {
    continuous_fragility_index(m1, s1, k1, m2, s2, k2,
                               conf.level = conf.level, n_sim = n_sim,
                               tol_mean = tol_mean, tol_sd = tol_sd)
  })
}

#' Tidyverse-Compatible Continuous Fragility Index
#'
#' Adds a Continuous Fragility Index column to a data frame of trial summary
#' statistics. Supports tidy evaluation.
#'
#' @param data A data frame or tibble.
#' @param mean1,sd1,n1 Unquoted column names for arm 1 mean, SD, and sample size.
#' @param mean2,sd2,n2 Unquoted column names for arm 2 mean, SD, and sample size.
#' @param conf.level,n_sim,tol_mean,tol_sd See [continuous_fragility_index()].
#' @param col_name Name of the output column (default `"continuous_fragility_index"`).
#'
#' @return The input data frame with an additional CFI column.
#' @export
tidy_continuous_fragility_index <- function(data,
                                            mean1, sd1, n1,
                                            mean2, sd2, n2,
                                            conf.level = 0.95,
                                            n_sim = 5L,
                                            tol_mean = 0.01,
                                            tol_sd = 0.01,
                                            col_name = "continuous_fragility_index") {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  col_name_sym <- rlang::sym(col_name)
  data %>%
    dplyr::mutate(
      !!col_name_sym := continuous_fragility_index_vec(
        {{ mean1 }}, {{ sd1 }}, {{ n1 }},
        {{ mean2 }}, {{ sd2 }}, {{ n2 }},
        conf.level = conf.level, n_sim = n_sim,
        tol_mean = tol_mean, tol_sd = tol_sd
      )
    )
}
